### ISSUE TITLE
Failed to activate the glua-autocomplete package

### ISSUE THREAD

**Issue by arifeld** [JohnnyCrazy/glua-autocomplete#3]
Just tried installing the package, but get this error when trying to install:

Have I missed something?

---

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [glua-autocomplete](https://github.com/JohnnyCrazy/glua-autocomplete) package 0.2.2

### Stack Trace

Failed to activate the glua-autocomplete package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at Object.consumeProvider (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/autocomplete-plus/lib/main.js:89:27)
    at Object.consumeProvider_2_0 (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/autocomplete-plus/lib/main.js:66:23)
    at Provider.module.exports.Provider.provide (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/package.js:258:22)
    at C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/package.js:99:21)
    at C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/package-manager.js:695:42)
    at C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:/ProgramData/Ari/atom/app-1.23.2/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  2x -5:43.8.0 editor:newline (input.hidden-input)
     -5:42.8.0 core:backspace (input.hidden-input)
     -5:41.4.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -5:40.9.0 core:backspace (input.hidden-input)
     -5:40.1.0 editor:newline (input.hidden-input)
     -5:39.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
  3x -5:37 core:backspace (input.hidden-input)
     -5:34.7.0 core:select-all (input.hidden-input)
     -5:34.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -5:25 settings-view:open (input.hidden-input)
     -2:31.2.0 settings-view:install-packages-and-themes (div.package-detail.panels-item)
     -2:25.1.0 core:confirm (input.hidden-input)
     -1:43.4.0 editor:newline (input.hidden-input)
     -1:41.2.0 core:backspace (input.hidden-input)
     -1:40.9.0 core:move-right (input.hidden-input)
  2x -1:40.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
glua-autocomplete 0.2.2 
```

**Comment by arifeld** [comment]
Actually, installing the linter by FPTje seemed to have fixed it. Nevermind then!
